import 'dart:io';

import 'package:excel/excel.dart' as xls;
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/bill_record.dart';
import '../models/meter.dart';
import 'calculation_service.dart';

class ExportService {
  static final _dateFmt = DateFormat('dd MMM yyyy');

  /// Builds a PDF report for one meter's full history and saves it to the
  /// app's documents directory. Returns the saved file.
  static Future<File> exportMeterHistoryToPdf(
    Meter meter,
    List<BillRecord> bills,
  ) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              'Meter Guardian — ${meter.name}',
              style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
            ),
          ),
          if (meter.location != null)
            pw.Text('Location: ${meter.location}'),
          if (meter.meterNumber != null)
            pw.Text('Meter Number: ${meter.meterNumber}'),
          pw.SizedBox(height: 12),
          pw.Table.fromTextArray(
            headers: [
              'Billing Month',
              'Bill Reading',
              'Current Reading',
              'Units Used',
              'Avg/Day',
              'Started',
            ],
            data: bills.map((b) {
              final calc = CalculationService.calculate(b, targets: meter.slabTargets);
              return [
                b.billingMonth,
                b.presentReading.toStringAsFixed(0),
                b.currentReading?.toStringAsFixed(0) ?? '-',
                calc.unitsUsed?.toStringAsFixed(1) ?? '-',
                calc.averagePerDay?.toStringAsFixed(2) ?? '-',
                b.meterStartDateTime != null
                    ? _dateFmt.format(b.meterStartDateTime!)
                    : '-',
              ];
            }).toList(),
            cellStyle: const pw.TextStyle(fontSize: 9),
            headerStyle: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 16),
          pw.Text(
            'Generated by Meter Guardian on ${_dateFmt.format(DateTime.now())}',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final safeName = meter.name.replaceAll(RegExp(r'[^\w]+'), '_');
    final file = File('${dir.path}/meter_guardian_${safeName}_history.pdf');
    await file.writeAsBytes(await doc.save());
    return file;
  }

  /// Builds an Excel workbook for one meter's full history.
  static Future<File> exportMeterHistoryToExcel(
    Meter meter,
    List<BillRecord> bills,
  ) async {
    final workbook = xls.Excel.createExcel();
    final sheetName = 'History';
    final sheet = workbook[sheetName];
    workbook.delete('Sheet1');

    final headers = [
      'Billing Month',
      'Bill Reading',
      'Previous Reading',
      'Current Reading',
      'Units Used',
      'Avg Units/Day',
      'Meter Start Date',
      'Issue Date',
      'Due Date',
    ];
    sheet.appendRow(headers.map((h) => xls.TextCellValue(h)).toList());

    for (final b in bills) {
      final calc = CalculationService.calculate(b, targets: meter.slabTargets);
      sheet.appendRow([
        xls.TextCellValue(b.billingMonth),
        xls.DoubleCellValue(b.presentReading),
        xls.DoubleCellValue(b.previousReading),
        b.currentReading != null
            ? xls.DoubleCellValue(b.currentReading!)
            : xls.TextCellValue('-'),
        calc.unitsUsed != null
            ? xls.DoubleCellValue(calc.unitsUsed!)
            : xls.TextCellValue('-'),
        calc.averagePerDay != null
            ? xls.DoubleCellValue(calc.averagePerDay!)
            : xls.TextCellValue('-'),
        xls.TextCellValue(
          b.meterStartDateTime != null ? _dateFmt.format(b.meterStartDateTime!) : '-',
        ),
        xls.TextCellValue(_dateFmt.format(b.issueDate)),
        xls.TextCellValue(b.dueDate != null ? _dateFmt.format(b.dueDate!) : '-'),
      ]);
    }

    final dir = await getApplicationDocumentsDirectory();
    final safeName = meter.name.replaceAll(RegExp(r'[^\w]+'), '_');
    final file = File('${dir.path}/meter_guardian_${safeName}_history.xlsx');
    final bytes = workbook.encode();
    if (bytes != null) {
      await file.writeAsBytes(bytes);
    }
    return file;
  }
}
